; Default controls - R36S style (with function button)

[ppsspp_pause]
files = /opt/ppsspp/backupforromsfolder/ppsspp/PSP/SYSTEM/controls.ini, /roms/psp/ppsspp/PSP/SYSTEM/controls.ini, /roms2/psp/ppsspp/PSP/SYSTEM/controls.ini
operation = replace_line
match = ^Pause\s*=.*$
replace = Pause = 10-106

[ppsspp_prev_slot]
files = /opt/ppsspp/backupforromsfolder/ppsspp/PSP/SYSTEM/controls.ini, /roms/psp/ppsspp/PSP/SYSTEM/controls.ini, /roms2/psp/ppsspp/PSP/SYSTEM/controls.ini
operation = replace_line
match = ^Previous Slot\s*=.*$
replace = Previous Slot = 10-196:10-188

[ppsspp_next_slot]
files = /opt/ppsspp/backupforromsfolder/ppsspp/PSP/SYSTEM/controls.ini, /roms/psp/ppsspp/PSP/SYSTEM/controls.ini, /roms2/psp/ppsspp/PSP/SYSTEM/controls.ini
operation = replace_line
match = ^Next Slot\s*=.*$
replace = Next Slot = 10-196:10-191

[ppsspp_reset]
files = /opt/ppsspp/backupforromsfolder/ppsspp/PSP/SYSTEM/controls.ini, /roms/psp/ppsspp/PSP/SYSTEM/controls.ini, /roms2/psp/ppsspp/PSP/SYSTEM/controls.ini
operation = replace_line
match = ^Reset\s*=.*$
replace = Reset = 10-196:10-4010

[retroarch_menu]
files = /home/ark/.config/retroarch/retroarch.cfg, /home/ark/.config/retroarch/retroarch.cfg.bak, /home/ark/.config/retroarch32/retroarch.cfg, /home/ark/.config/retroarch32/retroarch.cfg.bak
operation = replace_line
match = ^input_menu_toggle_btn\s*=\s*.*$
replace = input_menu_toggle_btn = "16"

[retroarch_prev_slot]
files = /home/ark/.config/retroarch/retroarch.cfg, /home/ark/.config/retroarch/retroarch.cfg.bak, /home/ark/.config/retroarch32/retroarch.cfg, /home/ark/.config/retroarch32/retroarch.cfg.bak
operation = replace_line
match = ^input_state_slot_decrease_btn\s*=\s*.*$
replace = input_state_slot_decrease_btn = "3"

[retroarch_next_slot]
files = /home/ark/.config/retroarch/retroarch.cfg, /home/ark/.config/retroarch/retroarch.cfg.bak, /home/ark/.config/retroarch32/retroarch.cfg, /home/ark/.config/retroarch32/retroarch.cfg.bak
operation = replace_line
match = ^input_state_slot_increase_btn\s*=\s*.*$
replace = input_state_slot_increase_btn = "2"

[retroarch_reset]
files = /home/ark/.config/retroarch/retroarch.cfg, /home/ark/.config/retroarch/retroarch.cfg.bak, /home/ark/.config/retroarch32/retroarch.cfg, /home/ark/.config/retroarch32/retroarch.cfg.bak
operation = replace_line
match = ^input_reset_btn\s*=\s*.*$
replace = input_reset_btn = "7"

[mupen64_pause]
files = /home/ark/.config/mupen64plus/mupen64plus.cfg
operation = replace_line
match = ^Joy Mapping Pause\s*=.*$
replace = Joy Mapping Pause = "J0B16"

[mupen64_next_slot]
files = /home/ark/.config/mupen64plus/mupen64plus.cfg
operation = replace_line
match = ^Joy Mapping Increment Slot\s*=.*$
replace = Joy Mapping Increment Slot = "J0B12/B2"

[mupen64_reset]
files = /home/ark/.config/mupen64plus/mupen64plus.cfg
operation = replace_line
match = ^Joy Mapping Reset\s*=.*$
replace = Joy Mapping Reset = "J0B12/B7"

[yabasanshiro_menu]
files = /opt/yabasanshiro/input.cfg
operation = replace_line
match = ^\s*<input name="select" type="button" id=".*" value="1" />$
replace =\t\t<input name="select" type="button" id="16" value="1" />